name: 'Neocities Deploy'
author: 'Felix Mattick'
branding:
  icon: 'upload-cloud'
  color: 'orange'
description: 'Deploy a static site to Neocities with the Neocel command-line tool'
inputs:
  directory:
    description: 'The directory to deploy'
    required: true
    default: '.'
  neocities_token:
    description: 'Your Neocities API token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.neocities_token }}
